---
title: "Prod graphics"
author: "Duc-Quang Nguyen | swissinfo.ch"
date: " 2018"
output: 
  html_document:
    code_folding: show
    echo: TRUE
    warning: FALSE
    message: FALSE
    toc: yes
    toc_depth: 3
    theme: simplex
---

<span style="border-bottom:3px solid red;">masculin</span>
<span class="underl dblue">safasd</span>

```{r setup, include=FALSE}
cleanOutput <- T
teaserify <- F
export_iscoCodeAndName <- F

require(lintr)
library(tidyverse)
library(magrittr)
library(stringr)
library(knitr)
library(countrycode)
library(swiMap)
library(swiTheme)
library(readxl)

### Interactive 
library(htmltools)
library(swiRcharts)
library(highcharter)
require(viridis)
library(sp)     ## Provides basic spatial classes/methods, incl. SpatialLines
library(rgeos)  

# Personnes actives occupées de 15 ans ou plus selon la profession exercée (nomenclature: NSP 2000), le sexe et la nationalité
raw.xls <- "data/su-f-40.02.03.02.01.03.20.xlsx"
column_names <- c('division',	'classe', 'groupe', 'genre', 'description', 
                  'total', 'hommes', 'femmes', 'suisses', 'étrangers')
column_types <- c('text', 'text', 'text', 'numeric', 'text', 
                  'numeric', 'numeric', 'numeric', 'numeric', 'numeric')

translation.file <- "input/Job gender - txt.csv"


## flip codes: men -> women
code_sub.sante <- c("864.01", "861.03", "862.04", "865.03", "862.03", "862.07") # sante
code_sub.edu  <- c("846.04", "843.01", "846.05") # education et enseignement 
code_sub.sci  <- c("851.03", "851.01", "853.01") #sciences sociales, humaines, naturelles, physiques et exactes
code_sub.art  <- c("822.01", "824.09", "824.07") # Professions artistiques
code_sub.mgmt <- c( "711.04", "721.03", "721.02", "751.04", "751.02") #management, de l'administration, de la banque et des assurances et professions judiciaires
code_sub.mgmt <- c(code_sub.mgmt, "521.01", "521.03", "521.02") # com

## close to flip
code_sub.nf <- c("861.01", "751.01", "721.04", "211.03")

### steady codes
#2 Professions de l'industrie et des arts et métiers (sauf construction) # 3 Professions de la technique et de l'informatique # 4 Professions de la construction et de l'exploitation minière
code_ste.man <- c("253.02", "311.04", "412.04", "211.02", "111.01", "291.03", "211.01", "532.04")  
code.ste.wom <- c("844.01", "831.02", "862.01", "865.07", "812.01", "865.04", "862.08", "114.02", "845.01", "861.02")

```

```{r data load & wrangle, warning = F, message = F, include=FALSE, cache = F}
sheets <- c("1970", "1980", "1990", "2000", "2010", "2013", "2016")

data.read <- sheets %>% map_df(function(sheet) {
  xl.read <- read_excel(
    raw.xls, sheet = sheet, range = "A5:J525", 
    col_names = column_names, col_types = column_types) %>% 
    mutate(year = as.numeric(sheet))
  xl.read[-1,]
})

# Put the isco codes into one column, add a column for the isco level
data <- data.read %>% 
  mutate(
    division = ifelse(is.na(division), "", division),
    classe = ifelse(is.na(classe), "", classe),
    groupe = ifelse(is.na(groupe), "", groupe),
    genre = ifelse(is.na(genre), "", genre) %>% as.character()
  ) %>%
  unite(division, classe, groupe, genre, col = "code", sep ="") %>%
  mutate(niveau = ifelse(str_length(code) >= 4, 4, str_length(code))) %>%
  select(code, niveau, everything()) %>%
  mutate(share_femmes = femmes/total, share_suisses = suisses/total) 

# order job description
data %<>% mutate(description = fct_reorder(description, as.numeric(code)))

# drop some columns
data %<>% select(-étrangers, -suisses, -share_suisses) %>%
  mutate(share_hommes = 1 - share_femmes)

txt <- loadTranslation(translation.file) 
```

```{r export isco codes}
if(export_iscoCodeAndName) {
  data %>% filter(
    code %in% c(code_sub.sante, code_sub.edu, code_sub.sci, code_sub.art, code_sub.mgmt, code_sub.nf, code_ste.man, code.ste.wom)) %>%
    select(code, description) %>% 
    unique() %>%
  write_csv(path = "iscoCode2Job_tmp.csv")
}
```

```{r plot}
code.sub <- "861.01"
#code.sub <- "253.02"
lang <- 'FR'
chart.height <- 200
bg.colour <-  "#f2f2f2"
title <- T

plot_code <- function(data, code.sub, titled = T) {
  dd <- data %>% filter(code == code.sub) 
  
  jobLabel <- txt[code.sub, lang]
  stopifnot(length(jobLabel) > 0, !is.null(jobLabel))
  
  dd %<>% select(-code, -niveau, -total, -hommes, -femmes, -description) %>%
    rename(femmes = share_femmes, hommes = share_hommes) %>%
    gather(sex, value, -year) %>%
    mutate(sex = as.factor(sex)) %>%
    arrange(year, sex) %>%
    mutate(
      value = value * 100
    )
  # absolute values for tooltip
  dd2 <-  data %>% filter(code == code.sub) %>% 
    select(-code, -niveau, -total, -share_hommes, -share_femmes, -description) %>%
    gather(sex, abs, -year) %>%
    mutate(sex = as.factor(sex)) %>%
    arrange(year, sex) %>%
    mutate(
      abs = round(abs * 1000)
    )
  
  dd.f <- dd %>% filter(sex == "femmes")
  
  dd.range <- dd %>% spread(sex, value)
  
  ### Find intersect ###
  # 1 find intersect https://stackoverflow.com/questions/31404679/can-ggplot2-find-the-intersections-or-is-there-any-other-neat-way

  # 2 using sp rgeos
  #https://stackoverflow.com/questions/21647982/how-to-get-the-intersection-point-of-two-vector
  f1 <-  SpatialLines(list(Lines(Line(
    dd %>% filter(sex == "femmes", !is.na(value)) %>% select(-sex) %>% as.matrix()
    ), "A")))
  f2 <-  SpatialLines(list(Lines(Line(
    dd %>% filter(sex == "hommes", !is.na(value)) %>% select(-sex) %>% as.matrix()
    ), "A")))
  gIts <- gIntersection(f1, f2)
  if(!is.null(gIts)) {
      minV <- coordinates(gIts)[1,'x']    
  }
  # if flip occurred
  flip <- F

  if(length(unique(dd.f$value >= 50)) > 1) {
    flip <- T
    its <- tibble(year = minV, femmes = 50, hommes = 50)
    
    dd.range1 <- bind_rows(
      dd.range %>% filter(year < minV, !is.na(femmes)),
      its
    )
    dd.range2 <- bind_rows(
      its,
      dd.range %>% filter(year > minV )
    )
    col1 <- ifelse(all(dd.range1$hommes >= dd.range1$femmes), "#4c6570", "#b15953")
    col2 <- ifelse(all(dd.range$hommes >= dd.range$femmes), "#4c6570", "#b15953")
  } else {
    col1 <- ifelse(all(dd.range$hommes >= dd.range$femmes), "#4c6570", "#b15953")
  }
  
  #tooltip
  dd <- left_join(dd, dd2)

  dd %<>% mutate(
    tp = str_c(
    '<table class="table">',
    '<tr><td><em>', dd$year,'</b></td><td>', txt[as.character(dd$sex), lang], '</em></td></tr>',
    '<tr><td>', round(dd$value, 1), '%</td><td>',  dd$abs, ' ', txt['emplois', lang], '</td></tr>',
    '</table>')
  )

  if(flip) {
    hc <- highchart(height = chart.height) %>%  
      hc_add_series(dd.range1, "arearange", hcaes(x = year, low = hommes, high = femmes), 
                    enableMouseTracking = F, lineWidth = 0, fillColor = hex_to_rgba(col1, 0.5),
                    marker = list(enabled = F)) %>%
      hc_add_series(dd.range2, "arearange", hcaes(x = year, low = hommes, high = femmes), 
                    enableMouseTracking = F, lineWidth = 0, fillColor = hex_to_rgba(col2, 0.5),
                    marker = list(enabled = F)) %>%
      hc_add_series(dd, "line", hcaes(x = year, y = value, group= sex, tp = tp),
                    marker = list(enabled = F,
                                  states = list(hover = list(enabled = F))), lineWidth = 2, 
                    color = c( "#b15953", "#4c6570"))
      
  } else {
    hc <- highchart(height = chart.height) %>%  
      hc_add_series(dd.range, "arearange", hcaes(x = year, low = hommes, high = femmes), 
                    enableMouseTracking = F, lineWidth = 0, fillColor = hex_to_rgba(col1, 0.5),
                    marker = list(enabled = F)) %>%
      hc_add_series(dd, "line", hcaes(x = year, y = value, group= sex, tp = tp),
                    marker = list(enabled = F, 
                                  states = list(hover = list(enabled = F))), lineWidth = 2, 
                    color = c( "#b15953", "#4c6570"))
  }
  hc2 <- hc %>%
    hc_add_theme(hc_theme_swi) %>%
    hc_legend(enabled = F) %>%
    hc_tooltip(
      formatter = JS("function() { return this.point.tp; }"),
      useHTML = T,
      hideDelay = 0,
      style = list(padding = 3, fontSize = "0.7em")
    ) %>%
    hc_yAxis(
      min = 0, max = 100, tickAmount = 3, opposite = ifelse(lang == "AR", T, F),
      useHTML = T, labels = list(format = '{value} %', style = list(fontSize = ifelse(titled, "0.8em", 0)), 
                                 align = ifelse(lang == "AR", "left", "right"))
    ) %>%
    hc_xAxis(
      gridLineWidth = 0.7, lineColor = "#CEC6B9", gridZIndex = -1, tickLength = 0, 
      labels = list(y = 13, enabled =  ifelse(titled, T, F)), reversed = ifelse(lang == "AR", T, F)
    ) 
  
  if(titled) {
    hc2 %<>% hc_title(
      text = as.character(jobLabel), 
      style = list("fontSize" = "1em", "color" = '#193442', fontWeight = "normal"),
      floating = T, align = ifelse(lang == "AR", "right", "left"), 
      useHTML = T, x = ifelse(lang == "AR", -25, 27), y = -32
    ) %>%
      hc_chart(
        #backgroundColor = bg.colour,
        spacing = list(45, 2, 17, 4)
        # , borderRadius = 4,
        # borderColor = "white", borderWidth = 1
      )    
  }    
  
  hc2
}
```

```{r plot grid chart}

for(lang in colnames(txt)) {
  
  p1 <- code_sub.sante %>% map(~ plot_code(data, .x))
  p2 <- code_sub.edu %>% map(~ plot_code(data, .x))
  p3 <- code_sub.sci %>% map(~ plot_code(data, .x))
  p4 <- code_sub.art %>% map(~ plot_code(data, .x))
  p5 <- code_sub.mgmt %>% map(~ plot_code(data, .x))
  
  p6 <- code_sub.nf %>% map(~ plot_code(data, .x))
  p7 <- code_ste.man %>% map(~ plot_code(data, .x))
  p8 <- code.ste.wom  %>% map(~ plot_code(data, .x))
  
  #plots <- lapply(code_sub.sante), function(iso) plotArea(dd, iso))
  
  source <- paste0(
    txt['source', lang], ": ",
    htmlLink( "https://www.bfs.admin.ch/bfs/fr/home/statistiques/travail-remuneration/activite-professionnelle-temps-travail/actifs-occupes/profession-situation-profession.assetdetail.4362786.html", txt['source.name', lang] ), " | ",
    txt['code', lang], ": ", htmlLink("https://github.com/jbkunst/highcharter", txt['code.name', lang]),
    " | swissinfo.ch | ",
    htmlLink("https://twitter.com/duc_qn", "@duc_qn"), " ", txt['inspiredBy', lang], " ",
    htmlLink("http://flowingdata.com/2017/09/11/most-female-and-male-occupations-since-1950/", "Flowing Data")
  )
  
  save_html(
    tags$html(
      dir = ifelse(lang == "AR", "rtl", "ltr"),
      tags$head(includeHTML(style_swi_highcharter_centered()), includeCSS(swi_highlight_css())),
      h2(HTML(txt["main.title1", lang])),
      div(class = "descr", HTML(
        paste0(txt['descr1', lang], " ", txt['descr2', lang]))),
      br(),
      h3(HTML(txt['h3.1', lang])),
      br(),
      div(class = "graphic", hw_grid(p1, ncol = 3, rowheight = chart.height)),
      br(),
      h3(HTML(txt['h3.2', lang])),
      br(),
      div(class = "graphic", hw_grid(p2, ncol = 3, rowheight = chart.height)),
      br(),
      h3(HTML(txt['h3.3', lang])),
      br(),
      div(class = "graphic", hw_grid(p3, ncol = 3, rowheight = chart.height)),
      br(),
      h3(HTML(txt['h3.4', lang])),
      br(),
      div(class = "graphic", hw_grid(p4, ncol = 3, rowheight = chart.height)),
      br(),
      h3(HTML(txt['h3.5', lang])),
      br(),
      div(class = "graphic", hw_grid(p5, ncol = 3, rowheight = chart.height)),
      
      br(),br(),
      h2(HTML(txt["main.title2", lang])),
      br(),
      div(class = "descr", HTML(txt['descr2', lang])),
      div(class = "graphic", hw_grid(p6, ncol = 4, rowheight = chart.height)),
      
      div(id = "cite", HTML(source)),
      HTML(iframeresizer)
    ),
    file =  paste0("jobGender_flip_", lang, ".html"), libdir = "js")  
  
    save_html(
    tags$html(
      dir = ifelse(lang == "AR", "rtl", "ltr"),
      tags$head(includeHTML(style_swi_highcharter_centered()), includeCSS(swi_highlight_css())),
      h2(HTML(txt["main.title3", lang])),
      div(class = "descr", HTML(
        paste0(txt['descr2', lang]))),
      br(),
      h3(HTML(txt['h3.1b', lang])),
      br(),
      div(class = "graphic", hw_grid(p7, ncol = 4, rowheight = chart.height)),
      br(),
      h3(HTML(txt['h3.2b', lang])),
      br(),
      div(class = "graphic", hw_grid(p8, ncol = 4, rowheight = chart.height)),
      div(id = "cite", HTML(source)),
      HTML(iframeresizer)
    ),
    file =  paste0("jobGender_steady_", lang, ".html"), libdir = "js")  
  
}

```

```{r move production graphics}
if (cleanOutput) {
  files <- c("jobGender_.*html", "js")

  if (!dir.exists("output/bak")) {
    dir.create("output/bak")
  } else {
    list.files("output/bak/", full.names = T, recursive = T) %>% file.remove()
  }
  ori.files <- list.files("output", full.names = T)[list.files("output") != "bak"]
  file.copy(ori.files, to = "output/bak/", recursive = T)
  unlink(ori.files, recursive = T)

  files_tomove <- lapply(files, function(x) list.files(pattern = x)) %>% unlist()
  file.copy(files_tomove, "output", recursive = T)
  unlink(files_tomove, recursive = T)
}
```

```{r teaser}
if(teaserify) {
  teaser <- c(code_sub.sante, code_sub.edu, code_sub.sci, code_sub.art, code_sub.mgmt, code_sub.sante) %>% map(~ plot_code(data, .x, titled = F))

  save_html(
    tags$html(
      tags$head(includeHTML(style_swi_highcharter_centered() )),
    div(class = "graphic", hw_grid(teaser, ncol = 6, rowheight = chart.height))
  ),
  file = "teaser.html", libdir = "js")  
    
}
```

```{r linting}
lintr::lint(knitr::current_input())
```
